name: PLAZMER-ENGINE
version: ${version}
main: t.me.p1azmer.engine.NexEngine
author: "plazmer"
website: "t.me/p1azmer"
description: "Plugin Engine"
api-version: 1.17
softdepend: [ Vault ]
load: STARTUP
folia-supported: true
libraries:
  - it.unimi.dsi:fastutil:8.5.11
  - com.zaxxer:HikariCP:5.0.1
  - com.cjcrafter:foliascheduler:0.6.3
